Repository kobotoolbox/kobocat, pull requests merged in 2020-06, with the labels that each got.

#592 Improved MetaData files upload and delete.
  onadata/apps/api/viewsets/metadata_viewset.py
  onadata/apps/logger/models/attachment.py
  onadata/apps/logger/models/xform.py
  onadata/apps/main/models/meta_data.py
  onadata/libs/filters.py
Labels: bug-fix

#613 Use 150K iterations when hasing passwords…
  onadata/libs/utils/hashers.py
  onadata/settings/common.py
Labels: high priority

#615 Increased request body & file upload max size
  onadata/settings/common.py
Labels: enhancement

#617 Prevent listing all users and public forms
  onadata/apps/api/permissions.py
  onadata/apps/api/viewsets/user_viewset.py
Labels: critical
