Repository kobotoolbox/kobocat, pull requests merged in 2021-03, with the labels that each got.

#685 Updated the formList to return version data
  onadata/libs/serializers/xform_serializer.py
Labels: enhancement

#680 [Python3 and Django2.2 upgrade] part 3 - Bulk update: remove object inheritance
  onadata/apps/api/mongo_helper.py
  onadata/apps/api/permissions.py
  onadata/apps/logger/factory.py
  onadata/apps/logger/tests/test_simple_submission.py
  onadata/apps/logger/xform_fs.py
  onadata/apps/logger/xform_instance_parser.py
  onadata/apps/main/models/audit.py
  onadata/apps/restservice/RestServiceInterface.py
  onadata/apps/viewer/pandas_mongo_bridge.py
  onadata/apps/viewer/xls_writer.py
  onadata/libs/filters.py
  onadata/libs/mixins/anonymous_user_mixin.py
  onadata/libs/mixins/anonymous_user_public_forms_mixin.py
  onadata/libs/mixins/labels_mixin.py
  onadata/libs/mixins/multi_lookup_mixin.py
  onadata/libs/mixins/object_lookup_mixin.py
  onadata/libs/mixins/openrosa_headers_mixin.py
  onadata/libs/mixins/view_permission_mixin.py
  onadata/libs/mixins/xform_id_string_lookup.py
  onadata/libs/models/clone_xform.py
  onadata/libs/templates/rest_framework_swagger/index.html
  onadata/libs/utils/briefcase_client.py
  onadata/libs/utils/csv_reader.py
  onadata/libs/utils/export_tools.py
  onadata/libs/utils/log.py
  onadata/libs/utils/redis_helper.py
Labels: api, technical-debt

#681 [Python3 and Django2.2 upgrade] part 5 - Updated docker image with non-root user
  Dockerfile
  dependencies/pip/dev.txt
  dependencies/pip/prod.txt
  dependencies/pip/requirements.txt
  docker/init.bash
  docker/run_celery.bash
  docker/run_celery_beat.bash
  docker/run_uwsgi.bash
  docker/run_uwsgi_wrong_port_warning.bash
  docker/setup_cron.bash
  docker/setup_pydev_debugger.bash
  docker/sync_static.bash
  requirements/README.md
  requirements/base.pip
  requirements/dev.pip
  requirements/s3.pip
  requirements/ses.pip
Labels: api, technical-debt

#692 Remove old SMS model functions and run migrations
  onadata/apps/api/tests/viewsets/test_briefcase_api.py
  onadata/apps/api/viewsets/xform_viewset.py
  onadata/apps/logger/migrations/0017_remove_xform_sms.py
  onadata/apps/logger/models/xform.py
  onadata/apps/logger/tests/test_briefcase_api.py
  onadata/apps/main/tests/test_user_id_string_unique_together.py
  onadata/libs/serializers/xform_serializer.py
  onadata/libs/utils/logger_tools.py
Labels: technical-debt

#695 GitHub actions for Python 3
  .failing-travis.yml
  .github/workflows/pytest.yml
  .travis.yml
  onadata/apps/api/tests/viewsets/test_briefcase_api.py
  onadata/apps/api/tests/viewsets/test_connect_viewset.py
  onadata/apps/logger/migrations/0017_remove_xform_sms.py
  onadata/apps/logger/tests/test_briefcase_api.py
  onadata/apps/main/tests/test_user_id_string_unique_together.py
  onadata/libs/data/query.py
  onadata/libs/data/tests/test_tools.py
  onadata/settings/base.py
  onadata/settings/testing.py
  onadata/settings/travis_ci.py
Labels: enhancement
