Repository kobotoolbox/kobocat, pull requests merged in 2021-08, with the labels that each got.

#754 Do not validate referrer by default with one time authentication token
  onadata/apps/api/models/one_time_auth_token.py
Labels: bug-fix

#758 SubmissionCounter bug fix
  onadata/apps/logger/migrations/0020_submission_counter_timestamp_as_date.py
  onadata/apps/logger/models/instance.py
  onadata/apps/logger/models/submission_counter.py
  onadata/libs/utils/logger_tools.py
Labels: bug-fix, backend

#761 Empty/corrupted superuser stats report fix
  onadata/apps/logger/tasks.py
Labels: high priority, bug-fix, backend
