Repository kobotoolbox/kobocat, pull requests merged in 2021-05, with the labels that each got.

#702 Fix docs typo
  onadata/apps/api/viewsets/data_viewset.py
Labels: bug-fix

#708 Fix argparse config for sync_mongo
  onadata/apps/viewer/management/commands/sync_mongo.py
Labels: high priority

#710 Added max_time_ms to mongo queries
  onadata/apps/survey_report/views.py
  onadata/apps/viewer/models/parsed_instance.py
  onadata/libs/utils/export_tools.py
  onadata/libs/utils/logger_tools.py
  onadata/settings/common.py
Labels: high priority

#711 Added missing api endpoint
  onadata/apps/main/tests/test_form_api.py
  onadata/apps/main/urls.py
  onadata/apps/main/views.py
Labels: api

#720 Removed recaptcha client dependency and registration HTML templates
  dependencies/pip/dev.txt
  dependencies/pip/prod.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  onadata/libs/templates/registration/activate.html
  onadata/libs/templates/registration/activation_complete.html
  onadata/libs/templates/registration/activation_email.txt
  onadata/libs/templates/registration/activation_email_subject.txt
  onadata/libs/templates/registration/login.html
  onadata/libs/templates/registration/password_change_done.html
  onadata/libs/templates/registration/password_change_form.html
  onadata/libs/templates/registration/password_reset_complete.html
  onadata/libs/templates/registration/password_reset_confirm.html
  onadata/libs/templates/registration/password_reset_done.html
  onadata/libs/templates/registration/password_reset_email.html
  onadata/libs/templates/registration/password_reset_form.html
  onadata/libs/templates/registration/registration_closed.html
  onadata/libs/templates/registration/registration_complete.html
  onadata/libs/templates/registration/registration_form.html
  onadata/libs/templates/registration/test_template_name.html
  onadata/settings/base.py
Labels: technical-debt

#706 Kobocat support for xform sync
  kobocat-template/templates/profile.html
  onadata/apps/main/views.py
Labels: high priority

#714 Validate metadata uploads
  kobocat-template/templates/show_form_settings.html
  onadata/apps/main/views.py
  onadata/libs/serializers/metadata_serializer.py
  onadata/settings/common.py
  requirements/dev.pip
Labels: api, enhancement, high priority
