Repository kobotoolbox/kobocat, pull requests merged in 2021-06, with the labels that each got.

#723 Add validation on XForms when creating metadata objects
  onadata/apps/api/permissions.py
  onadata/apps/api/tests/viewsets/test_abstract_viewset.py
  onadata/apps/api/tests/viewsets/test_metadata_viewset.py
  onadata/libs/filters.py
  onadata/libs/serializers/metadata_serializer.py
Labels: api, bug-fix

#694 Add a flag `from_kpi` on media files
  onadata/apps/main/migrations/0003_add_field_from_kpi_to_metadata.py
  onadata/apps/main/models/meta_data.py
  onadata/libs/serializers/metadata_serializer.py
  onadata/libs/serializers/xform_serializer.py
Labels: api

#726 Add validation metadata content type support to `beta`
  kobocat-template/templates/base.html
  kobocat-template/templates/legacy_banner.html
  kobocat-template/templates/profile.html
  kobocat-template/templates/published_surveys.html
  kobocat-template/templates/show_form_settings.html
  onadata/apps/api/permissions.py
  onadata/apps/api/tests/viewsets/test_abstract_viewset.py
  onadata/apps/api/tests/viewsets/test_metadata_viewset.py
  onadata/apps/main/models/meta_data.py
  onadata/apps/main/static/css/screen.css
  onadata/apps/main/views.py
  onadata/libs/filters.py
  onadata/libs/serializers/metadata_serializer.py
  onadata/libs/serializers/xform_serializer.py
  onadata/libs/templates/registration/logout.html
  onadata/settings/base.py
Labels: api

#728 Fix form media permissions
  Dockerfile
  README.md
  onadata/apps/main/views.py
Labels: high priority

#729 Add guidance and redirect links to KPI for legacy form and data views
  kobocat-template/templates/base.html
  kobocat-template/templates/legacy_banner.html
  kobocat-template/templates/outdated_data_view.html
  kobocat-template/templates/outdated_link_guidance.html
  kobocat-template/templates/show.html
  onadata/apps/main/urls.py
  onadata/apps/main/views.py
Labels: high priority

#738 Improve metadata content type validation
  dependencies/pip/dev.in
  dependencies/pip/dev.txt
  dependencies/pip/prod.txt
  dependencies/pip/requirements.in
  dependencies/pip/requirements.txt
  onadata/apps/api/tests/viewsets/test_metadata_viewset.py
  onadata/libs/serializers/metadata_serializer.py
Labels: api, bug-fix

#741 Update supported media types
  onadata/settings/base.py
Labels: api, bug-fix
