Repository kobotoolbox/kobocat, pull requests merged in 2023-09, with the labels that each got.

#892 Remove public access to project API endpoint
  README.md
  REMOVALS.md
  onadata/apps/api/permissions.py
  onadata/apps/api/tests/viewsets/test_abstract_viewset.py
  onadata/apps/api/tests/viewsets/test_xform_viewset.py
  onadata/apps/logger/tests/test_form_submission.py
  onadata/apps/main/tests/test_base.py
Labels: api, technical-debt, backend

#894 Prevent SKIP_HEAVY_MIGRATIONS warning unless running the relevant migrations
  onadata/apps/main/migrations/0011_drop_old_kpi_tables.py
Labels: bug-fix, backend

#895 Create null xform instances for DailyXFormSubmissionCounter
  onadata/apps/logger/management/commands/populate_submission_counters.py
  onadata/apps/logger/migrations/0028_add_user_to_daily_submission_counters.py
  onadata/apps/logger/migrations/0029_populate_daily_xform_counters_for_year.py
  onadata/apps/logger/models/daily_xform_submission_counter.py
  onadata/apps/logger/models/instance.py
  onadata/apps/logger/models/xform.py
  onadata/apps/logger/tests/models/test_xform_submission_counters.py
Labels: backend
