Repository kobotoolbox/kobocat, pull requests merged in 2023-08, with the labels that each got.

#889 Retain daily submission counters for one year
  onadata/apps/logger/management/commands/populate_submission_counters.py
  onadata/apps/logger/migrations/0028_populate_daily_xform_counters_for_year.py
  onadata/settings/base.py
Labels: backend

#882 Add footer disclaimer to Open Rosa XML
  onadata/apps/api/viewsets/xform_list_api.py
  onadata/apps/form_disclaimer/__init__.py
  onadata/apps/form_disclaimer/migrations/0001_initial.py
  onadata/apps/form_disclaimer/migrations/__init__.py
  onadata/apps/form_disclaimer/models.py
  onadata/apps/logger/models/xform.py
  onadata/libs/serializers/xform_serializer.py
  onadata/libs/utils/xml.py
  onadata/settings/base.py
Labels: backend

#886 Code refactoring: Use `default_storage` instead of `get_storage_class()()`
  onadata/apps/api/tests/viewsets/test_briefcase_api.py
  onadata/apps/api/tools.py
  onadata/apps/logger/management/commands/create_image_thumbnails.py
  onadata/apps/logger/management/commands/move_media_to_s3.py
  onadata/apps/logger/models/xform.py
  onadata/apps/logger/tasks.py
  onadata/apps/logger/tests/test_importing_database.py
  onadata/apps/main/tests/test_csv_export.py
  onadata/apps/main/tests/test_form_exports.py
  onadata/apps/viewer/models/export.py
  onadata/apps/viewer/views.py
  onadata/libs/utils/export_tools.py
  onadata/libs/utils/image_tools.py
  onadata/libs/utils/logger_tools.py
  onadata/libs/utils/viewer_tools.py
Labels: enhancement, backend

#887 Allow only OpenRosa endpoints with not-validated passwords
  kobocat-template/templates/restricted_access.html
  onadata/apps/api/tests/viewsets/test_user.py
  onadata/apps/api/tests/viewsets/test_xform_submission_api.py
  onadata/apps/api/viewsets/connect_viewset.py
  onadata/apps/main/migrations/0012_add_validate_password_flag_to_profile.py
  onadata/apps/main/models/user_profile.py
  onadata/koboform/redirect_middleware.py
  onadata/libs/http/__init__.py
  onadata/libs/http/response.py
  onadata/libs/utils/logger_tools.py
  onadata/libs/utils/middleware.py
  onadata/settings/base.py
Labels: api, blocked, backend
