Repository kobotoolbox/kobocat, pull requests merged in 2023-10, with the labels that each got.

#896 Improve `update_attachment_storage_bytes` management command
  onadata/apps/logger/management/commands/update_attachment_storage_bytes.py
  onadata/apps/logger/tasks.py
Labels: enhancement, backend

#897 Regroup storage counter calculation in the same DB transaction
  onadata/apps/logger/management/commands/move_media_to_s3.py
  onadata/apps/logger/signals.py
  onadata/libs/utils/logger_tools.py
Labels: backend

#900 Make user not nullable in DailyXFormSubmissionCounter
  onadata/apps/logger/migrations/0030_backfill_lost_monthly_counters.py
  onadata/apps/logger/migrations/0031_remove_null_user_daily_counters.py
  onadata/apps/logger/migrations/0032_alter_daily_submission_counter_user.py
  onadata/apps/logger/models/daily_xform_submission_counter.py
  onadata/apps/logger/utils.py
Labels: backend

#792 [ TASK-163 ] Keep attachments list up-to-date when editing a submission
  onadata/apps/api/tests/viewsets/test_abstract_viewset.py
  onadata/apps/api/tests/viewsets/test_attachment_viewset.py
  onadata/apps/logger/management/commands/soft_delete_orphan_attachments.py
  onadata/apps/logger/management/commands/update_attachment_storage_bytes.py
  onadata/apps/logger/migrations/0033_add_deleted_at_field_to_attachment.py
  onadata/apps/logger/models/attachment.py
  onadata/apps/logger/models/instance.py
  onadata/apps/logger/models/xform.py
  onadata/apps/logger/signals.py
  onadata/apps/logger/xform_instance_parser.py
  onadata/apps/main/tests/fixtures/transportation/instances/transport_with_attachment/1335783522563.jpg
  onadata/apps/main/tests/fixtures/transportation/instances/transport_with_attachment/IMG_2235.JPG
  onadata/apps/main/tests/fixtures/transportation/instances/transport_with_attachment/transport_with_attachment.xml
  onadata/apps/main/tests/fixtures/transportation/instances/transport_with_attachment/transport_with_attachment_edit.xml
  onadata/apps/main/tests/fixtures/transportation/transportation_with_attachment.xls
  onadata/apps/main/tests/fixtures/userone/userone_with_dot_name_fields.xls
  onadata/apps/main/tests/fixtures/userone/userone_with_dot_name_fields.xml
  onadata/apps/main/tests/test_csv_export.py
  onadata/apps/viewer/views.py
  onadata/libs/serializers/attachment_serializer.py
  onadata/libs/tests/mixins/make_submission_mixin.py
  onadata/libs/utils/logger_tools.py
Labels: enhancement, api, backend

#901 Fix failing ZIP exports
  onadata/libs/utils/viewer_tools.py
Labels: bug-fix

#903 Fix 500 error when fetching data with a date range
  onadata/apps/api/tests/viewsets/test_data_viewset.py
  onadata/apps/api/viewsets/xform_viewset.py
Labels: bug-fix
